#sudo: required
branches:
  only:
  - master
  - release
language: python
python:
- '3.4'
#before_install:
#- sudo add-apt-repository ppa:koffeinflummi/armake -y
#- sudo apt-get update -q
#- sudo apt-get install armake -y
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
  fi
script:
#- make
- python3 tools/sqf_validator.py
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    python3 tools/deploy.py;
  fi
env:
  global:
  - secure: KH2+h0nNqef/BWLHwQuvksE8NMKE81yzdmzR6d+K8N7wPpe00tNLtFSVkgic+OReeRruLb23DOZTpJ94lctdC3QKDrgmiE83x3BbBw/KrMoUpI1qDfX5hiTybQJp5Ys41jnMyG/jIda9H4PJR2ABg0CJgrGS+cY8zGZXfsMXX709UzE7iXtKJJbQMgutU2AG8cRzc9FU28Xcx765YcM33jnbYEe/bUa8071LgCWEnC+Ena/KUjyK7lNw0LYJVaLxFObYfacHzrNb+X87WVSYeVjYQxhCzPvm/r9VTWV3EX12bG8Aoj4oSFNIIDlx+fKCCjYILrCccLxH8T5YVs6tVj+REOCT/aIvjXrII6EulTDb/tNsLQ/IckQ68jC3hSq4mTsfZGvxQz+UrwD98Exulh1O/mp45hrI8oLSCCw3tBnSxuxcYixQBSsGWNfrrU8tqRIFSLJwF3hC4z154+jrDkpbhgE1TgCkXvw9+58xg9q8bf6ORHyQjVnUtodexmmQybvea9aWyY5zGBdI0Nq9rzWkFpHyqfujUFM7e5v4fZ0ICJI6zvraMO+HpQldujJF5wD7rsLMsrn6T+MIrecNpuiJIzZpQwHzuh8YKTuYb4TNvWkb1PqWlz+/b1ET0E2K813QSSH40S1fIorr+GKcRZ/6tcx8FjMBEnRzGUbvcFw=
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: YlNSW4zvv1XTDrVBL8b5bWC97u6KBDDmOe81gIZNefmQ5A3y4eUSLKNUrzKWvqDwTSKzytmMfpsv/+urE/mFRAyhVb0t0/BlzdjbyA0z9Qn/mjkMQFomB5M+LPZNtq2sMorGBUiMCBQE2YtEZeLu6/sbfLYN6H4iyUxILefcAVReUi1s8VBBhsit0Wk67RoEGuaIdUnKsqynNoA4NctiVkXXx6MyP0+JCQphbGBBK+HtEkjPuWqKxBYfHbQMvIhhi6dbtCf023Up4j44fNpvASPeC+bsxg3XKUw9wSBGT8DF838gbwxL8jL62MlHIHFHi9rikq/f1j+V+ftWTGBnIJ0FElExYbl2Ck1voSkPzfrU7O654Kv7LXf4mWJe9l5IGP1stf+5m5vDfVlXh8VrAQwxNxJMHsL/dyzxiLHrvTXtblKBaquRjUQNAgbR3D2RJDjMUPb5yuR5yw5QrqKYdpJyUKN5b/uWi0TDATQZ4g3j9LEuY3FhHu42xfj74lFLb5KX1UKRUdFN3lyKi7LynuhtPE8ySBtNYjeUlq/mwMv5o1wwmMHTmrKvnLkXBvlJHOxCaKh/G08tkl3RncyPAuxf/7FK3Zf2PS5z9IWENxtanbBpI0CgcXmmfQkkDpRrbU02VqyLA4fehKWwVaiHYO9RltjWkUsPhd1a5sDerQg=
    on_success: change
    on_failure: always
    on_start: never
